preset: psr2

enabled:
  - strict
  - strict_param

enabled:
  - long_array_syntax
  - strict
  - unalign_double_arrow

disabled:
  - short_array_syntax
  - concat_without_spaces
  - no_empty_lines_after_phpdocs
