sudo: false
dist: trusty
language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_install:
  - mkdir -p build/logs
  - composer self-update

install:
  - composer clear-cache
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-text

notifications:
  email: false

matrix:
  fast_finish: true
