sudo: false

language: php

php:
  - 5.6
  - 7
  - hhvm

before_install:
  - composer self-update

install:
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-text

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
