sudo: false
language: php

php:
  - 7.3
  - 7.4
  - 8.0

before_install:
  - mkdir -p build/logs
  - composer self-update

install: 
  - |
    if [ $(phpenv version-name) != '8.0' ]; then
      travis_retry composer install
    fi
    if [ $(phpenv version-name) == '8.0' ]; then
      travis_retry composer install --ignore-platform-req=php
    fi

script:
  - ./vendor/bin/phpunit --coverage-text

notifications:
  email: false

matrix:
  fast_finish: true
